Document: wl-mirror
Title: Debian wl-mirror Manual
Author: <insert document author here>
Abstract: This manual describes what wl-mirror is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wl-mirror/wl-mirror.sgml.gz

Format: postscript
Files: /usr/share/doc/wl-mirror/wl-mirror.ps.gz

Format: text
Files: /usr/share/doc/wl-mirror/wl-mirror.text.gz

Format: HTML
Index: /usr/share/doc/wl-mirror/html/index.html
Files: /usr/share/doc/wl-mirror/html/*.html
